worldName: 99th_Precinct
timezone: Europe/Amsterdam
worldDimensions: 500
itemOffset: 25
gameStart: '2021-10-31T00:00:00'
gameEnd: '2021-11-01T00:00:00'
realTimeCycle:
  active: true
  sunrise: 7:30
  sunset: 17:07
allowEnderchest: false
season: 1
kit:
  enabled: true
  cooldown: 300
antiGriefing: 20