name: HalloweenHeistPlugin
main: nl._99th_dutchies.halloween_heist.HalloweenHeistPlugin
version: 1.0
description: ""
website: https://99th-dutchies.nl/
authors: [ "99th_DutchVoid" ]
softdepend: [ "ViaBackwards" ]
api-version: 1.16
commands:
  kit:
    description: Obtain a default kit
    usage: /kit
  trade:
    description: Trade 3 redstone for 1 glowstone dust
    usage: /trade [amount]
