name: HalloweenHeistPlugin
main: nl._99th_dutchies.halloween_heist.HalloweenHeistPlugin
version: 1.2
description: ""
website: https://99th-dutchies.nl/
authors: [ "99th_DutchVoid" ]
softdepend: [ "ViaBackwards" ]
api-version: 1.16
commands:
  kit:
    description: Obtain a default kit
    usage: /kit
  location:
    description: Get the current location of the Heist Object
    usage: /location
  trade:
    description: Trade (3 redstone => 1 glowstone dust or 5 rotten flesh => 1 nether wart)
    usage: /trade [glowstone / netherwart] [amount]
