name: HalloweenHeistPlugin
main: nl._99th_dutchies.halloween_heist.HalloweenHeistPlugin
version: 1.3.3
description: ""
website: https://99th-dutchies.nl/
authors: [ "99th_DutchVoid" ]
softdepend: [ "ViaBackwards" ]
api-version: 1.16
commands:
  kit:
    description: Obtain a default kit
    usage: /kit
  location:
    description: Get the current location of the Heist Object
    usage: /location
  trade:
    description: Trade
    usage: /trade [material] [amount]
  team:
    description: Create a team or assign a player to a team. For console use only!
    usage: /team create [team] | /team add [team] [player]
